#index:
#    path: /
#    controller: App\Controller\DefaultController::index



index:
    path:     /
    controller: App\Controller\HomeController::index


#  fr_index:
#      path:     fr/
 #     controller: App\Controller\HomeController::index

#  eng_index:
#      path:     en/
#      controller: App\Controller\HomeController::indexeng